# Generated by Django 3.1.2 on 2020-10-31 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('city', models.TextField(null=True)),
                ('publisher', models.TextField(null=True)),
                ('year', models.TextField(null=True)),
                ('series', models.TextField(null=True)),
                ('tags', models.TextField(null=True)),
                ('article', models.TextField(null=True)),
                ('age_rating', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('age', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BookTake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_id', models.TextField()),
                ('barcode', models.BigIntegerField()),
                ('take_at', models.DateTimeField()),
                ('return_at', models.DateTimeField()),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.condition')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.reader')),
            ],
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_id', models.TextField()),
                ('barcode', models.BigIntegerField()),
                ('classification_id', models.TextField()),
                ('sigles_id', models.FloatField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.catalog')),
            ],
        ),
    ]
