# Generated by Django 3.1.2 on 2020-10-31 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finance_type', models.TextField()),
                ('schedule_type', models.TextField(null=True)),
                ('service_name', models.TextField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('duration', models.TextField()),
                ('duration_unit', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField()),
                ('short_name', models.TextField()),
                ('street_name', models.TextField(null=True)),
                ('underground_name', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.FloatField()),
                ('sex', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('rating', models.FloatField()),
                ('challenge_complete', models.BooleanField(null=True)),
                ('accepted', models.BooleanField(null=True)),
                ('declined', models.BooleanField(null=True)),
                ('decline_reason', models.TextField(null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('enrolment_at', models.DateTimeField(null=True)),
                ('expulsion_at', models.DateTimeField(null=True)),
                ('reason', models.TextField(null=True)),
                ('planned_start_date', models.DateField(null=True)),
                ('planned_end_date', models.DateField(null=True)),
                ('next_service_relation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='next_service_relations', to='data.servicerelation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.serviceorganization')),
                ('prev_service_relation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prev_service_relations', to='data.servicerelation')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='data.servicerequest')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='data.service')),
                ('service_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.serviceuser')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='data.serviceclass')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.serviceorganization'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.serviceclass'),
        ),
    ]
