# Generated by Django 3.1.2 on 2020-10-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_remove_event_mosru_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceuser',
            name='sex',
            field=models.TextField(null=True),
        ),
    ]
