# Generated by Django 3.1.2 on 2020-10-31 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='mosru_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicerelation',
            name='service_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='data.serviceuser'),
        ),
    ]
