# Generated by Django 3.1.2 on 2020-10-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20201031_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='cover_url',
            field=models.TextField(null=True),
        ),
    ]
