# Generated by Django 3.1.2 on 2020-10-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_catalog_cover_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
