# Generated by Django 3.1.2 on 2020-10-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_quote_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='MlBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.IntegerField()),
                ('author', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('city', models.TextField(null=True)),
                ('publisher', models.TextField(null=True)),
                ('year', models.TextField(null=True)),
                ('series', models.TextField(null=True)),
                ('tags', models.TextField(null=True)),
                ('article', models.TextField(null=True)),
                ('age_rating', models.TextField(null=True)),
                ('mean', models.FloatField(null=True)),
                ('count', models.FloatField(null=True)),
                ('rating', models.FloatField(null=True)),
            ],
        ),
    ]
