# Generated by Django 3.1.2 on 2020-10-31 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_mlrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preds_number', models.IntegerField(null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.catalog')),
            ],
        ),
    ]
