# Generated by Django 3.1.2 on 2020-10-31 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_predictioncounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField()),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.reader')),
            ],
        ),
    ]
